[logging]

# log_level = 'WARN'
# log_format = '%(asctime)s - [%(levelname)s] - %(funcName)s - %(message)s'

# log_to_console = true

# log_to_file = false
# log_file_dir = '.'
# log_file_name = 'stego.log'
# log_file_max_bytes = 5242880  # 5M
# log_files_count = 10

[files]
extracts_folder = 'assets/extracts'
covers_folder = 'assets/covers'
stegos_folder = 'assets/stegos'
messages_folder = 'assets/messages'
analysis_folder = 'assets/analysis'